# Generated by Django 5.1.2 on 2024-10-16 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='appeal_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
