# Generated by Django 5.1.2 on 2024-10-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='ticket_title',
            field=models.TextField(default=''),
        ),
    ]
