# Generated by Django 5.1.2 on 2024-10-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_useranme_support_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
