# Generated by Django 5.1.2 on 2024-10-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_support_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='ticket_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
