# Generated by Django 5.1.2 on 2024-10-18 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_annoucement_alter_support_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='payout_account',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='payout_method',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
