# Generated by Django 5.1.2 on 2024-10-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_image',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/'),
        ),
    ]
