# Generated by Django 5.1.2 on 2024-10-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alert_alert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_sound',
            field=models.FileField(blank=True, null=True, upload_to='mp3s/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_image',
            field=models.ImageField(default='alerts/default_donation.gif', upload_to='alerts/'),
        ),
    ]
