# Generated by Django 5.1.2 on 2024-10-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alert_alert_sound_alter_alert_alert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_sound',
            field=models.FileField(default='mp3s/default_alert_sound.mp3', upload_to='mp3s/'),
        ),
    ]
