# Generated by Django 5.1.2 on 2024-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_donation_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_page',
            name='profile_picture',
            field=models.ImageField(default='profiles/default__user_pfp.jpg', upload_to='profiles/'),
        ),
    ]
