# Generated by Django 5.1.2 on 2024-10-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_donation_donation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='transcation_uid',
            new_name='transaction_uuid',
        ),
    ]
