# Generated by Django 5.1.2 on 2024-10-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_transcation_uid_donation_transaction_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='alert_image',
            new_name='alert_image_level_1',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_sound',
            new_name='alert_sound_1',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_image_level_2',
            field=models.ImageField(default='alerts/default_donation.gif', upload_to='alerts/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_image_level_3',
            field=models.ImageField(default='alerts/default_donation.gif', upload_to='alerts/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_sound_2',
            field=models.FileField(default='mp3s/default_alert_sound.mp3', upload_to='mp3s/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_sound_3',
            field=models.FileField(default='mp3s/default_alert_sound.mp3', upload_to='mp3s/'),
        ),
    ]
